### PR TITLE
Change globmatch to accept an empty list as `patterns`

### PR DESCRIPTION
**Pull request by frankier**
This allows nice usage with click multiple e.g.

```
@click.option("-x", "--exclude", multiple=True)
...
                if globmatch(my_path, exclude):
```

### CODE REVIEW

**Comment by facelessuser** [comment]
I have a couple issues with this.

1. This only fixes your specific use case, and in turn, creates inconsistencies with other functions such as `globfilter` and `glob` which all still won't accept an empty list. Not to mention the `fnmatch` library also doesn't accept empty lists in its function.

2. This could easily be solved if the user simply validated their own inputs. `globmatch` accepts strings and/or a list of strings. It doesn't accept a list with no strings as this is a nonsense input for the functions as it gives it nothing for it to do. A valid input must be given to the functions, and I can't see why we'd allow an empty list as we don't accept omitting a string altogether when no list is given.

**Comment by frankier** [comment]
>>> all([])
True
>>> any([])
False

terse because i have an arm injury

**Comment by facelessuser** [comment]
> terse because i have an arm injury

I'm not sure what we are describing here

**Comment by frankier** [comment]
forget it

**Comment by facelessuser** [comment]
Okay...

**Pull request closed without merging**
