### PR TITLE
Fix pathlib match behavior related to dot files

### PR DESCRIPTION
**Pull request by facelessuser**
Pathlib should not be limited by dotfiles on the left as evaluation
order is from right to left.

### CODE REVIEW

**Comment by facelessuser** [comment]
Needs tests

**Comment by facelessuser** [comment]
I've thought about this more. And I'm remembering why I did it this way. By default, Python's match enables dot glob. I do not think this should always be the default, so we used MATCHBASE logic which is sensitive to leading dots on file names. This allows you to ignore hidden files if you want to. Now it will have a difficult time if `.` or `..` is present, but that is okay I think. We will leave this as is, but instead, document it better.

**Comment by facelessuser** [comment]
Re-reading Python's documentation, it clearly states that `match` performs matches from the right, meaning right to left.

With that in mind, it appears we do need to adjust this. While it is similar to match base, it doesn't exactly work the same, so we should treat it differently.

**Comment by facelessuser** [comment]
So this is what I think happened. Python's pathlib library wrote `rglob` which appends `**/` to the path, and since rglob enables dot matching by default, it returns everything (except `..` of course - also `.`, but pathlib strips that out anyways).

So `match` is meant to match everything as well. Evaluating it in reverse is kind of a shortcut that allows it to match everything that `rglob` does. But it also matches `..`.

I don't know if matching `..` is intentional or just a side-effect, but it is present none the less.

So in our case, `match` is performed, much like `rglob` with `**/` appended to the start. It will not match dot files or files in dot folders unless a pattern is specifically given that allows it. But when `DOTGLOB` is enabled, `match` will match everything except `..` and `.`.

So, I'm okay with `match` not matching hidden files when `DOTGLOB` is not enabled. It allows you to exclude hidden files if you have no interest in them. The question is whether when `DOTGLOB` is enabled whether it should match `.` and `..`, and I guess when `DOTGLOB` is not enabled as well.

**Comment by facelessuser** [comment]
I think we'll just stick with ensuring the feel is "right to left" as `pathlib` states. That means left most dot files will not prevent a match if the pattern doesn't force them to be evaluated. People can always use `globmatch` to do whatever they want if `match` isn't working as they wish (that is what I do). The idea is to provide a `pathllib` that is familiar but with added flexibility, which is what we do. `rglob` and `match` are carried over from the original `pathlib`, so we'll maintain their functionality with the added benefit of getting to choose whether certain features are enabled via flags. Even if the right and left matching is a little odd if you want to not match hidden files, some people will probably want it to work the same as the original `pathlib` describes it.

**Comment by facelessuser** [comment]
This now matches Python's `match` behavior. You can still configure dot matching, globstar, etc. of the pattern portion, but it will match right to left as stated in pathlib.

If a user is frustrated by this fix and somehow relied on our deviation from prior to the fix, they could use the internal, undocumented flag `_EXTMATCHBASE`. Can't promise it will always be there, but the real way to get it back is just to write your pattern and prepend `**/` and enable `GLOBSTAR`. No special function needed 🙂. I guess the one advantage of of the prior behavior is that it also calculated when your pattern was relative and needed the `**/`. It is also likely that I change this and I never hear a peep from anyone.

**Comment by facelessuser** [comment]
@gir-bot lgtm

**Comment by lorengordon** [comment]
peep 😆

**Pull request merged**
